title: Dr. Praveendra Singh
description: Assistant Professor of Mathematics
theme: minima

markdown: kramdown
kramdown:
  math_engine: mathjax

sass:
  style: compressed

header_pages:
 - about.md
 - research.md
 - publications.md
 - teaching.md
 - resources.md
 - videos.md
 - projects.md
 - problems.md
 - blog.md
 - contact.md
